[Service]
Environment=RESEND_API_KEY=re_gVqdDM1r_KnBPu8Jb1jaDy1aifKmBQQGC
Environment="MAIL_FROM=Pan-o-Rama <noreply@pan-o-rama.online>"
Environment=APP_BASE_URL=https://pan-o-rama.online
Environment=EMAIL_VERIFICATION_ENABLED=1
